title: Kimberly Batin
# logo: just in case i want to put photo
# description below image if there is
# from here: https://github.com/pages-themes/minimal?tab=readme-ov-file
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
