title: Kimberly's Portfolio
# logo: just in case i want to put photo
# description below image if there is
# from here: https://github.com/pages-themes/minimal?tab=readme-ov-file
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
description: Explore a collection of my projects and contributions. Feel free to browse through my repositories, and don’t hesitate to reach out if you have any questions or collaboration ideas. You can contact me via [LinkedIn](https://www.linkedin.com/in/batinkimberly/). Happy coding!
