title: Kimberly Batin
description: Explore a collection of my projects and contributions. Feel free to browse through my repositories, and don’t hesitate to reach out if you have any questions or collaboration ideas. You can contact me via <a href="https://www.linkedin.com/in/batinkimberly/">LinkedIn</a>.
# logo: just in case i want to put photo
# description below image if there is
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

author:
  name: "Kimberly Batin"
  github: "kbatin.github.io"
  linkedin: "https://www.linkedin.com/in/batinkimberly/"

